### ISSUE TITLE
Not working with my file

### ISSUE THREAD

**Issue by SamGG** [Bohdan-Khomtchouk/Microscope#10]
Thanks for this nice piece of software. I tried with the attached file, but I didn't get any heatmap in the heatmap tab and an error in the stats tab. Let me know what is wrong with my file.
Although the Excel screenshot is informative, you should provide a short and clear example file. But that's only my humble opinion.
[samples.csv.zip](https://github.com/Bohdan-Khomtchouk/Microscope/files/79557/samples.csv.zip)

**Comment by Bohdan-Khomtchouk** [comment]
There is nothing wrong with your file (whatsoever):

<img width="1437" alt="screen shot 2016-01-06 at 3 58 25 am" src="https://cloud.githubusercontent.com/assets/9893806/12138840/e4dd23a0-b429-11e5-9555-632fb8e593ba.png">

However, you cannot perform stats on this file b/c it contains negative values (raw gene expression values cannot, by default, be negative).

**Comment by SamGG** [comment]
Thanks for your answer.
a) I don't get the nice picture you show. I am using Firefox 42 on Mint Debian, Build identifier: Mozilla/5.0 (X11; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0. May be there is something with it. I will do a trial using RStudio later on.
b) Usually gene expression are log2 transformed and row centered, which leads to positive and negative values. Only positive values are raw values, that are not interesting without any transformation. Negative must be allowed.
Best.

**Comment by Bohdan-Khomtchouk** [comment]
Thank you for bringing this issue to my attention.  A log2 transformer utility will be incorporated into MicroScope shortly, as MicroScope is currently designed to handle raw (non-normalized) expression values only.  In the meantime, it would be helpful if you posted in this thread the RStudio error that you get when you load in the file on your machine.  Instructions for how to run MicroScope within RStudio are provided in the README.md of this repository.

**Comment by Bohdan-Khomtchouk** [comment]
As a temporary suggestion, you could safely undo your log2 normalization manually within Excel and then reupload this raw count file into MicroScope.  MicroScope's statistical apparatus will perform the log2 transformation automatically for you, and return a table consisting of logFC (fold change values), many of which will be negative (and many positive) to indicate up and down regulation.  See https://www.biostars.org/p/82699/ for more details.  To see the specifics of how MicroScope handles raw count files such as these, please visit the server.r code within this repository.

**Comment by SamGG** [comment]
Thanks for your answer. In the old days of micro-arrays, only log2 transformed were usually clustered.
Best.
