### ISSUE TITLE
pics

### ISSUE THREAD

**Issue by Bohdan-Khomtchouk** [Bohdan-Khomtchouk/Microscope#9]
<img width="1440" alt="picc1" src="https://cloud.githubusercontent.com/assets/9893806/12105623/74e1c930-b324-11e5-965e-08d523617f49.png">
<img width="1440" alt="picc2" src="https://cloud.githubusercontent.com/assets/9893806/12105624/771091be-b324-11e5-8676-e121ab2d84f7.png">
<img width="1440" alt="picc3" src="https://cloud.githubusercontent.com/assets/9893806/12105625/78933474-b324-11e5-8294-c6306f243f3b.png">

**Comment by sebastiancoin** [comment]
Huh?

**Comment by sebastiancoin** [comment]
closed #9?

**Comment by Bohdan-Khomtchouk** [comment]
Yes, to attach any sort of images in the Github README.md, you need to open
an issue and close it with the appropriate cloud IP.

Disregard any of this stuff, it's irrelevant.
